# # Install pre-commit hooks via
# pre-commit install

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.2.3
  hooks:
  - id: trailing-whitespace
    types: [python]
  - id: double-quote-string-fixer
    types: [python]


- repo: https://github.com/pre-commit/mirrors-yapf
  rev: v0.30.0
  hooks:
  # yapf = yet another python formatter
  - id: yapf
    name: yapf
    types: [python]
    exclude: >
      (?x)^(
          docs/.*|
      )$
    args: ['-i']

- repo: local
  hooks:

  # prospector: collection of linters
  - id: pylint
    name: pylint
    entry: pylint
    types: [python]
    language: system
    exclude: &exclude_files >
      (?x)^(
        .*/test_.*.py
      )$

  - id: version-number
    name: Check version numbers
    entry: python ./.github/check_version.py
    language: system
    files: '^(setup.json)|(aiida_zeopp/__init__.py)'
