#!/bin/bash
# piping through to singularity
set -e
SCRIPT_PATH="$( cd "$(dirname "$0")" ; pwd -P )"
singularity exec "${SCRIPT_PATH}/../ltalirz-singularity-recipe-zeopp-master-ansible.simg" /usr/local/bin/network "$@"
